language: python

python:
  - 3.6
  - 3.5

cache: pip

install:
  - pip install --upgrade pip
  - pip install -e .[develop] --progress-bar off
  - pip install sphinx==1.8.5
  - pip install m2r

script:
  - python setup.py test
  - cd docs && make html && mv ./build/html ./build/docs && rm -r ./build/doctrees && cd ..
  - cd docs/meta && python update_doc.py && cd ../..

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $DEPLOY_KEY
    keep-history: true
    repo: thu-coai/cotk_docs
    target-branch: master
    local-dir: ./docs/build
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    script: coveralls
    on:
      all_branches: true
      condition: true
