language: python

python:
  - 3.6

cache: pip

install:
  - pip install sphinx
  - pip install pytest-cov==2.4.0
  - pip install python-coveralls

script:
  - pip install -e .
  - py.test --cov=contk tests/ --cov-report term-missing
  - python ./models/run_tests.py
  - cd docs
  - make html
  - mv ./build/html ./build/docs
  - rm -r ./build/doctrees
  - cd ..

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $DEPLOY_KEY
    keep-history: true
    repo: thu-coai/contk_docs
    target-branch: master
    local-dir: ./docs/build
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    script: coveralls
    on:
      all_branches: true
      condition: true
